version: "3.1"
services:

  pgsql:
    container_name: Postgres
    image: postgres:13
    restart: always
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - ./pgsql/data:/var/lib/postgres/data
